package sound

import _ "embed"

// The cues are 16-bit mono PCM WAV at 22050 Hz, about 30 KB for the pair,
// generated by gencues.go in this directory. WAV rather than a compressed
// format because every system player decodes it, including the ALSA and
// PipeWire tools that decode nothing, which is what lets the probe list stay
// short and lets aplay be on it at all.

//go:embed assets/done.wav
var doneWAV []byte

//go:embed assets/needs-input.wav
var attentionWAV []byte

// cueAssets holds the embedded bytes for each cue.
var cueAssets = map[Cue][]byte{
	CueDone:      doneWAV,
	CueAttention: attentionWAV,
}

// cueFiles names each cue's spilled file. The name reaches a player's argv and
// sometimes a log, so it says what it is.
var cueFiles = map[Cue]string{
	CueDone:      "dartuios-done.wav",
	CueAttention: "dartuios-needs-input.wav",
}
